// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.edge_ai

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** The availability of the on-device generative AI model. */
enum class EdgeAiAvailability(val raw: Int) {
  /** The model is available and ready to use. */
  AVAILABLE(0),
  /**
   * The device supports the model, but it still needs to download (for
   * example, Android's Gemini Nano feature is downloadable/downloading).
   */
  DOWNLOADABLE(1),
  /**
   * The device supports the model, but the user hasn't enabled the
   * OS-level AI feature yet (for example, Apple Intelligence is turned
   * off).
   */
  NOT_YET_READY(2),
  /** The device or OS version doesn't support the on-device model. */
  UNAVAILABLE(3);

  companion object {
    fun ofRaw(raw: Int): EdgeAiAvailability? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The status of an on-device model download. */
enum class EdgeAiDownloadStatus(val raw: Int) {
  /** The download has started. */
  STARTED(0),
  /** The download is in progress. */
  IN_PROGRESS(1),
  /** The download finished and the model is ready to use. */
  COMPLETED(2);

  companion object {
    fun ofRaw(raw: Int): EdgeAiDownloadStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Optional parameters controlling how the model generates its response.
 *
 * Only fields supported by both Android and iOS are exposed here.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EdgeAiGenerationOptions (
  /**
   * Controls the randomness of the output. Higher values produce more
   * creative (less predictable) responses.
   */
  val temperature: Double? = null,
  /** The maximum number of tokens the model may generate in its response. */
  val maxOutputTokens: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EdgeAiGenerationOptions {
      val temperature = pigeonVar_list[0] as Double?
      val maxOutputTokens = pigeonVar_list[1] as Long?
      return EdgeAiGenerationOptions(temperature, maxOutputTokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      temperature,
      maxOutputTokens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EdgeAiGenerationOptions
    return MessagesPigeonUtils.deepEquals(this.temperature, other.temperature) && MessagesPigeonUtils.deepEquals(this.maxOutputTokens, other.maxOutputTokens)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.temperature)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxOutputTokens)
    return result
  }
  override fun toString(): String {
    return "EdgeAiGenerationOptions(temperature=$temperature, maxOutputTokens=$maxOutputTokens)"
  }
}

/**
 * A single download progress update.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EdgeAiDownloadProgress (
  /** The current status of the download. */
  val status: EdgeAiDownloadStatus,
  /**
   * The total number of bytes downloaded so far. Only populated when
   * [status] is [EdgeAiDownloadStatus.inProgress].
   */
  val bytesDownloaded: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EdgeAiDownloadProgress {
      val status = pigeonVar_list[0] as EdgeAiDownloadStatus
      val bytesDownloaded = pigeonVar_list[1] as Long?
      return EdgeAiDownloadProgress(status, bytesDownloaded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      bytesDownloaded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EdgeAiDownloadProgress
    return MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.bytesDownloaded, other.bytesDownloaded)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bytesDownloaded)
    return result
  }
  override fun toString(): String {
    return "EdgeAiDownloadProgress(status=$status, bytesDownloaded=$bytesDownloaded)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EdgeAiAvailability.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EdgeAiDownloadStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EdgeAiGenerationOptions.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EdgeAiDownloadProgress.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EdgeAiAvailability -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is EdgeAiDownloadStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is EdgeAiGenerationOptions -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is EdgeAiDownloadProgress -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface EdgeAiHostApi {
  fun checkAvailability(callback: (Result<EdgeAiAvailability>) -> Unit)
  /**
   * Stores [prompt] and [options] for the next `generateContentChunk` event
   * channel subscription to use.
   *
   * Event channels can't carry parameters, so callers must invoke this
   * immediately before listening to the `generateContentChunk` stream.
   */
  fun startGenerateContent(prompt: String, options: EdgeAiGenerationOptions?)

  companion object {
    /** The codec used by EdgeAiHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `EdgeAiHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EdgeAiHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.edge_ai.EdgeAiHostApi.checkAvailability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkAvailability{ result: Result<EdgeAiAvailability> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.edge_ai.EdgeAiHostApi.startGenerateContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String
            val optionsArg = args[1] as EdgeAiGenerationOptions?
            val wrapped: List<Any?> = try {
              api.startGenerateContent(promptArg, optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class DownloadProgressStreamHandler : MessagesPigeonEventChannelWrapper<EdgeAiDownloadProgress> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: DownloadProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.edge_ai.EdgeAiEventApi.downloadProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<EdgeAiDownloadProgress>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<EdgeAiDownloadProgress>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class GenerateContentChunkStreamHandler : MessagesPigeonEventChannelWrapper<String> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: GenerateContentChunkStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.edge_ai.EdgeAiEventApi.generateContentChunk"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<String>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<String>) {}

override fun onCancel(p0: Any?) {}
}
      
