// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// The availability of the on-device generative AI model.
enum EdgeAiAvailability {
  /// The model is available and ready to use.
  available,
  /// The device supports the model, but it still needs to download (for
  /// example, Android's Gemini Nano feature is downloadable/downloading).
  downloadable,
  /// The device supports the model, but the user hasn't enabled the
  /// OS-level AI feature yet (for example, Apple Intelligence is turned
  /// off).
  notYetReady,
  /// The device or OS version doesn't support the on-device model.
  unavailable,
}

/// The status of an on-device model download.
enum EdgeAiDownloadStatus {
  /// The download has started.
  started,
  /// The download is in progress.
  inProgress,
  /// The download finished and the model is ready to use.
  completed,
}

/// Optional parameters controlling how the model generates its response.
///
/// Only fields supported by both Android and iOS are exposed here.
class EdgeAiGenerationOptions {
  EdgeAiGenerationOptions({
    this.temperature,
    this.maxOutputTokens,
  });

  /// Controls the randomness of the output. Higher values produce more
  /// creative (less predictable) responses.
  double? temperature;

  /// The maximum number of tokens the model may generate in its response.
  int? maxOutputTokens;

  List<Object?> _toList() {
    return <Object?>[
      temperature,
      maxOutputTokens,
    ];
  }

  Object encode() {
    return _toList();  }

  static EdgeAiGenerationOptions decode(Object result) {
    result as List<Object?>;
    return EdgeAiGenerationOptions(
      temperature: result[0] as double?,
      maxOutputTokens: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EdgeAiGenerationOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(temperature, other.temperature) && _deepEquals(maxOutputTokens, other.maxOutputTokens);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EdgeAiGenerationOptions(temperature: $temperature, maxOutputTokens: $maxOutputTokens)';
  }
}

/// A single download progress update.
class EdgeAiDownloadProgress {
  EdgeAiDownloadProgress({
    required this.status,
    this.bytesDownloaded,
  });

  /// The current status of the download.
  EdgeAiDownloadStatus status;

  /// The total number of bytes downloaded so far. Only populated when
  /// [status] is [EdgeAiDownloadStatus.inProgress].
  int? bytesDownloaded;

  List<Object?> _toList() {
    return <Object?>[
      status,
      bytesDownloaded,
    ];
  }

  Object encode() {
    return _toList();  }

  static EdgeAiDownloadProgress decode(Object result) {
    result as List<Object?>;
    return EdgeAiDownloadProgress(
      status: result[0]! as EdgeAiDownloadStatus,
      bytesDownloaded: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EdgeAiDownloadProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(bytesDownloaded, other.bytesDownloaded);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EdgeAiDownloadProgress(status: $status, bytesDownloaded: $bytesDownloaded)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is EdgeAiAvailability) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is EdgeAiDownloadStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is EdgeAiGenerationOptions) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is EdgeAiDownloadProgress) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : EdgeAiAvailability.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : EdgeAiDownloadStatus.values[value];
      case 131:
        return EdgeAiGenerationOptions.decode(readValue(buffer)!);
      case 132:
        return EdgeAiDownloadProgress.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class EdgeAiHostApi {
  /// Constructor for [EdgeAiHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EdgeAiHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<EdgeAiAvailability> checkAvailability() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.edge_ai.EdgeAiHostApi.checkAvailability$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as EdgeAiAvailability;
  }

  /// Stores [prompt] and [options] for the next `generateContentChunk` event
  /// channel subscription to use.
  ///
  /// Event channels can't carry parameters, so callers must invoke this
  /// immediately before listening to the `generateContentChunk` stream.
  Future<void> startGenerateContent(String prompt, EdgeAiGenerationOptions? options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.edge_ai.EdgeAiHostApi.startGenerateContent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[prompt, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

Stream<EdgeAiDownloadProgress> downloadProgress( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel downloadProgressChannel =
      EventChannel('dev.flutter.pigeon.edge_ai.EdgeAiEventApi.downloadProgress$instanceName', pigeonMethodCodec);
  return downloadProgressChannel.receiveBroadcastStream().map((dynamic event) {
    return event as EdgeAiDownloadProgress;
  });
}
    
Stream<String> generateContentChunk( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel generateContentChunkChannel =
      EventChannel('dev.flutter.pigeon.edge_ai.EdgeAiEventApi.generateContentChunk$instanceName', pigeonMethodCodec);
  return generateContentChunkChannel.receiveBroadcastStream().map((dynamic event) {
    return event as String;
  });
}
    
