// The style `EdgeGenAIRewriter` rewrites text into.
//
// This is generated by Pigeon from `pigeons/messages.dart` — run
// `make pigeon` to regenerate it after making schema changes.
export 'src/messages.g.dart' show EdgeGenAIRewriteStyle;
