// The availability of an on-device generative AI feature, and the set of
// features the plugin exposes.
//
// These are generated by Pigeon from `pigeons/messages.dart` — run
// `make pigeon` to regenerate them after making schema changes.
export 'src/messages.g.dart' show EdgeGenAIAvailability, EdgeGenAIFeature;
