/// Optional parameters controlling how the on-device model generates its
/// response.
///
/// This is generated by Pigeon from `pigeons/messages.dart` — run
/// `make pigeon` to regenerate it after making schema changes.
export 'src/messages.g.dart' show EdgeAiGenerationOptions;
