/// A progress update for an on-device model download.
///
/// This is generated by Pigeon from `pigeons/messages.dart` — run
/// `make pigeon` to regenerate it after making schema changes.
export 'src/messages.g.dart' show EdgeAiDownloadProgress, EdgeAiDownloadStatus;
