import 'src/messages.g.dart';

// The parameter type enum is generated by Pigeon from
// `pigeons/messages.dart` — run `make pigeon` to regenerate it.
export 'src/messages.g.dart' show EdgeGenAIToolParameterType;

/// A single named parameter of an [EdgeGenAITool].
class EdgeGenAIToolParameter {
  EdgeGenAIToolParameter({
    required this.name,
    required this.description,
    this.type = EdgeGenAIToolParameterType.string,
    this.isRequired = true,
  });

  /// The parameter's name, as it appears in the arguments map.
  final String name;

  /// What the parameter means, so the model knows what to pass.
  final String description;

  /// The parameter's value type.
  final EdgeGenAIToolParameterType type;

  /// Whether the model must always provide this parameter.
  final bool isRequired;
}

/// A tool (function) the on-device model may call while generating a
/// response to an `EdgeGenAIPrompt.generateContent` call.
///
/// The [name], [description], and [parameters] are shown to the model so it
/// knows when and how to call the tool; [onCall] is the Dart implementation
/// that runs when it does.
///
/// On iOS this uses Foundation Models' native `Tool` support. Android's
/// ML Kit GenAI Prompt API has no native tool calling, so the plugin
/// emulates it there by instructing the model to reply with a tool-call
/// JSON object — treat tool calling on Android as best-effort: the small
/// on-device model may answer directly instead of calling a tool.
class EdgeGenAITool {
  EdgeGenAITool({
    required this.name,
    required this.description,
    this.parameters = const [],
    required this.onCall,
  });

  /// The tool's unique name (unique within one `EdgeGenAIPrompt` instance).
  final String name;

  /// What the tool does, so the model knows when to call it.
  final String description;

  /// The parameters the model should pass when calling the tool.
  final List<EdgeGenAIToolParameter> parameters;

  /// Runs the tool with the [arguments] the model provided (decoded from
  /// JSON) and returns the result text the model continues generating with.
  final Future<String> Function(Map<String, Object?> arguments) onCall;
}
