/// The availability of the on-device generative AI model.
///
/// This is generated by Pigeon from `pigeons/messages.dart` — run
/// `make pigeon` to regenerate it after making schema changes.
export 'src/messages.g.dart' show EdgeGenaiAvailability;
