// A progress update for an on-device model download.
//
// These are generated by Pigeon from `pigeons/messages.dart` — run
// `make pigeon` to regenerate them after making schema changes.
export 'src/messages.g.dart'
    show EdgeGenAIDownloadProgress, EdgeGenAIDownloadStatus;
